### ISSUE TITLE
Omnibus Embedding

### ISSUE THREAD

**Issue by j1c** [neurodata/graspy#10]
Write a function for omnibus embedding with following features:
  * Can take any number of matrices
  * Checks for same matrix dimensions

DoD:
  * Code + tests demonstrating that it works.

**Comment by jovo** [comment]
i'd recommend starting with 2 matrices, rather than any number.

@j1c who is assigned this?

**Comment by j1c** [comment]
This is assigned to me. It is part of the overall sprint 1 sprint now.

**Comment by jovo** [comment]
Yes. I meant test on 2 to start

**Comment by j1c** [comment]
See #39.
