### ISSUE TITLE
make graspy sklearn compliant/compatible

### ISSUE THREAD

**Issue by jovo** [neurodata/graspy#105]

**Comment by j1c** [comment]
Current implementations of embedding methods require some internal changes for it to pass the `check_estimator` function. The following have been modified to be sklearn compatible:
- [x] ASE
- [ ] LSE
- [ ] Omni
- [x] cMDS

**Comment by j1c** [comment]
As per Andreas, we cant test for complex inputs like lists or tensors for Omni so graspy will be **partially** sklearn compliant.
