### ISSUE TITLE
Pass to ranks - simple-all and simple-zero returns matrices with values > 1

### ISSUE THREAD

**Issue by j1c** [neurodata/graspy#107]
## Expected Behavior
PTR should always return values between 0 and 1, inclusive.

## Template Code
```GraSPy
import graspy
import numpy as np

np.random.seed(1)
A = graspy.simulations.er_np(100, 1.0, wt=np.random.exponential, wtargs=dict(scale=5))
np.max(pass_to_ranks(A, 'simple-all'))
>>>> 1.9797020297970203

np.max(pass_to_ranks(A, 'simple-nonzero')
>>>> 1.9996970003029997
```

## Your Environment
* Python version: 3.7.1
* GraSPy version: 0.0.1
* SciPy version: 1.2.0

**Comment by bdpedigo** [comment]
Was implemented the same as R code when it was written because we talked about doing some comparisons. That's why there is the factor of 2 in the code. I'm happy with removing it now

**Comment by j1c** [comment]
I actually dont think this is an issue with what was written. I believe the problem is within the ranking function. Let me investigate, but I do remember when I was playing with iris dataset where the "same" values weren't considered the same due to floating point issues (e.g. 1.5 != 1.5 cause the first one might be 1.500000000001 and the other might be 1.499999999).

**Comment by j1c** [comment]
Nevermind... Theres two different implementations of ptr in R-graphstats. One returns values in [0, 2] and the other returns values in [0, 1]..
