### ISSUE TITLE
ptr ranks need to be multiplied by 2

### ISSUE THREAD

**Issue by v715** [neurodata/graspy#135]
documentation for "simple-all" and "simple-nonzero" says that the transformed ranks should be multiplied by 2 but this is not done in the current code (see below)

```
# this snippet is from graspy.utils.ptr

elif method in ["simple-all", "simple-nonzero"]:
        non_zeros = graph[graph != 0]
        rank = rankdata(non_zeros)
        if method == "simple-all":
            normalizer = graph.size
        elif method == "simple-nonzero":
            normalizer = rank.shape[0]
        rank = rank / (normalizer + 1)
        graph[graph != 0] = rank
        return graph
```

the line `rank = rank / (normalizer + 1)` should be replaced with `rank = 2 *  rank / (normalizer + 1)`

**Comment by v715** [comment]
looking through some earlier versions of the pass_to_ranks function, I see that the  * 2 was previously implemented. why was this removed?

**Comment by bdpedigo** [comment]
I think it made more sense for everything to be scaled from 0 to 1.

We will change the docs accordingly unless you have a reason to prefer the
old implementation.

**Comment by v715** [comment]
I don't have a preference! my only issue was that the documentation made me believe that I was getting the wrong value

**Comment by j1c** [comment]
I dont think the answers to subsequent tasks should change given that the values are just scaled by sqrt(2) if you multiply by 2 in PTR. So your results should still be the same, if not, very similar.


On March 13, 2019 at 10:07:21 AM, Vivek Gopalakrishnan (notifications@github.com) wrote:

I don't have a preference! my only issue was that the documentation made me believe that I was getting the wrong value

**Comment by hhelm10** [comment]
NB: The reason that PTR typically scales things by two is so that if A is unweighted then PTR(A) = A. In terms of inference on the graph the scale shouldn't matter.
