### ISSUE TITLE
graph model fitting classes

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/graspy#142]
I'm writing classes to fit ER, SBM, DCSBM, RDPG to a particular graph, and then let you sample from it. Eventually, should support a priori and a posteriori cases, where applicable. 

What to do about weights, when applicable... @hhelm10 I know you have been dealing with empirical cdfs and sampling from them for SBM, correct? Do you calculate p for each block, sample edges, and then for the weights in that block sample randomly from the ecdf for that block? 

Other input into these classes welcome

**Comment by ebridge2** [comment]
I would non-parametric bootstrap as you describe. Fit a p for each block on the binarized graph, then sample the weights of nonzero edges as described. This would be semi parametric zero-inflated model.

That said, for sampling, i think it would be relatively easy to allow people to specify (a) a model for the structural properties of the graph (ie, ER, SBM, etc) with (b) parameters accordingly (ie, vertex communities), and (c) have another option and (d) kwarg list for the edge weight sampling model (ie, normal, poisson, model free) where the particular (a) and (c) specified indicate which model it is that the graphs are sampled from.
