### ISSUE TITLE
two truths experiments

### ISSUE THREAD

**Issue by hhelm10** [neurodata/graspy#149]
recreate two truths results (found here: https://arxiv.org/pdf/1808.07801.pdf) using graspy

**Comment by bdpedigo** [comment]
I dare you

**Comment by bdpedigo** [comment]
@jovo for this is there a particular figure or result that is most important? You also mention this for dos and dont's so I think a summer student may run this

My understanding is: 
- graphs sampled from 4 block SBM presented in the paper
- GMM o LSE on graphs
- GMM o ASE on graphs 
- ARI for how well ASE/LSE picks up left/right, grey/white splits

**Comment by bdpedigo** [comment]
https://www.pnas.org/content/116/13/5995.short

**Comment by jovo** [comment]
correct

**Comment by bdpedigo** [comment]
https://github.com/neurodata/dos_and_donts/blob/exp9/experiments/experiment_9/Two_truths_simulation_1.ipynb

https://github.com/neurodata/dos_and_donts/blob/exp9/experiments/experiment_9/Two_truths_simulation_2.ipynb
