### ISSUE TITLE
Implement hierarchical SBM

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/graspy#156]
you are working on this right @vikramc1 ?

**Comment by bdpedigo** [comment]
@vikramc1 did you ever start any code for this? I am considering implementing it if you haven't already

**Comment by vikramc1** [comment]
nope, you can go for it

**Comment by bdpedigo** [comment]
Note: if anyone needs this, I have code and simulations for this but not tested

**Comment by bdpedigo** [comment]
closing, will add into #299
