### ISSUE TITLE
bring seeded graph matching here

### ISSUE THREAD

**Issue by jovo** [neurodata/graspy#159]
see: https://github.com/neurodata/primitives-interfaces/tree/master/jhu_primitives/sgm

**Comment by bdpedigo** [comment]
@hhelm10 can you add a link to the paper for this too?

**Comment by hhelm10** [comment]
https://arxiv.org/pdf/1209.0367.pdf

**Comment by bdpedigo** [comment]
@hhelm10 you haven't done any work on this yet have you? Considering for a project for summer students

**Comment by hhelm10** [comment]
Negative.

Would be happy for someone else to do it :-)

Hayden

**Comment by bdpedigo** [comment]
Ok, no promises though

**Comment by jovo** [comment]
here is pytorch code for sgm: https://github.com/bkj/sgm
let's compare and improve ours?

@alyakin314 @bdpedigo

**Comment by hhelm10** [comment]
nb: bkj's implementation does not allow for multiple / random initializations

**Comment by bdpedigo** [comment]
@asaadeldin11 is doing this

**Comment by asaadeldin11** [comment]
I can confirm that I am working on this

**Comment by bdpedigo** [comment]
@asaadeldin11 could you just list what we will be evaluating you on, e.g. which of the SGM functionalities you will for sure have implemented by sprint 1, and how you will show it is correct

**Comment by asaadeldin11** [comment]
For sure I will be implementing hard seeding (algorithm 1). Based on jovos feedback on wednesday, he'd like me to focus on scipy with faq and what we have for sgm so far, and then work on padding and soft seeding. To prove in works, I will be replicating figure 2 and table 1 from Fishkind's sgm paper.

**Comment by bdpedigo** [comment]
closed by #323
