### ISSUE TITLE
let's be able to run gcca

### ISSUE THREAD

**Issue by jovo** [neurodata/graspy#169]

**Comment by bdpedigo** [comment]
@vikramc1  are you doing this?

**Comment by vikramc1** [comment]
Yes

**Comment by rflperry** [comment]
I ported over the Matlab code to python and have it working on one of my repos 
[here](https://github.com/rflperry/meditation/blob/master/src/features/gcca.py). I compared it to the matlab results and it seemed to line up.

**Comment by bdpedigo** [comment]
Closing since in mvlearn https://mvlearn.netlify.com/index.html
