### ISSUE TITLE
Do not install "tests" directory with this package

### ISSUE THREAD

**Issue by mitar** [neurodata/graspy#175]
## Expected Behavior

`pip3 install graspy` should create `/usr/local/lib/python3.6/dist-packages/graspy` directory.

## Actual Behavior

Also `/usr/local/lib/python3.6/dist-packages/tests` gets created. This is problematic, because `tests` is a very general name and could lead to conflicts. Also, there is no need to be installing tests on end-user machines.

## Your Environment
* Python version: 3.6.7
* GraSPy version: 0.0.2

**Comment by bdpedigo** [comment]
Thanks for the heads up, we will look into this

**Comment by bdpedigo** [comment]
Closed by #225
