### ISSUE TITLE
custom cmaps in heatmap plotting function

### ISSUE THREAD

**Issue by v715** [neurodata/graspy#179]
matplotlib lets you define custom colormaps ([this](https://matplotlib.org/api/_as_gen/matplotlib.colors.LinearSegmentedColormap.html) is one way)

I would like to pass these colormap objects to the graspy heatmap function, but I can't because they are required to be strings

https://github.com/neurodata/graspy/blob/92eaded5ac33f3880323cc39f4c99d9786fde0a0/graspy/plot/plot.py#L188-L191

can this be changed to allow custom colormaps?

**Comment by bdpedigo** [comment]
I agree with you. I also think we should have the `vmin` and `vmax` arguments in the matplotlib heatmap. 

Would you want to make a PR for this? If not just let us know.

**Comment by v715** [comment]
yeah i'll start working on a PR this weekend!

are considering allowing the user to specify `vmin` and `vmax`?

**Comment by bdpedigo** [comment]
Yeah that is what I mean, should be trivial to implement I think you just need to expose those kwargs (they are already apart of sns.heatmap I believe)

**Comment by bdpedigo** [comment]
@v715 I'm just checking whether you've worked on this or #183? Just curious because I may want these for a notebook I'm making soon, if not that's cool just let me know what you plan on doing

**Comment by v715** [comment]
haven't had a the chance yet, but im aiming to do it this Sunday

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
