### ISSUE TITLE
Implement dimselect, seeded graph matching

### ISSUE THREAD

**Issue by j1c** [neurodata/graspy#19]
write code, tests, and documentation for the following:
+ [x] dimensionality selection
+ [ ] joint graph embedding base on shangsi paper

DoD:
+ finished code with documentation, tests for each
+ travis integration for each function added

**Comment by jovo** [comment]
SGM is pretty complex, there are many variants of it.
if @bstadt is plannign on doing many-to-one, he should probably also engage in this.

**Comment by jovo** [comment]
what about pass-to-ranks? is that one of the transformatinos?

**Comment by j1c** [comment]
Closing. At this point, @bvarjavand isn't working on SGM and probably won't anytime soon.
