### ISSUE TITLE
Implement omni, clustering after embedding, plotting functions

### ISSUE THREAD

**Issue by j1c** [neurodata/graspy#20]
Write code, tests, and documentation for the following:
- [x] Omni
- [x] Clustering after embedding? GMM/MDS
- [x] Plotting
- [x] README.md
- [x] CONTRIBUTING.md
- [x] Setup sphinx script for generating docs

DoD:
- [x] Finished code with documentation, tests
- [x] Passing Travis
- [x] Nature compliant repo
- [x] Pypi package
- [x] Full documentation hosted by github

**Comment by jovo** [comment]
"implement" for GMM i assume means leverage sklearn?

consider a coherent plotting strategy for the whole repo, seaborn/plotly/bokeh, choose 1 collectively
