### ISSUE TITLE
Consider using n_init option for GClust

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/graspy#203]
There is a lot of variability in model fit just based on the random initialization of k-means to GMM, I think we should consider allowing the user to do some number of inits for each set of clustering parameters

**Comment by idc9** [comment]
I'm having this same issue on my data set e.g. the number selected by BIC is variable (5-15) across multiple runs. Unfortunately it's a private dataset so I can't put up an easy example of this.

I modified GaussianCluster to allow for n_init and this fixed the variability problem. I'm going to submit a PR with this enhancement.
