### ISSUE TITLE
GClust bug

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/graspy#205]
<img width="558" alt="Screen Shot 2019-06-22 at 3 46 06 PM" src="https://user-images.githubusercontent.com/25714207/59968259-eb346c80-9504-11e9-984c-8c13dff93a37.png">

should be `- self.min_components` rather than `- 1`

This causes an indexing error when `min_components` does not equal 1

**Comment by j1c** [comment]
Good catch. Will make a test for it as well.

Also just link the line directly in github rather than taking a screenshot
