### ISSUE TITLE
fix load_datasets when installed from PyPI

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/graspy#212]
## Expected Behavior
`graspy.datasets.load_drosophila_left` (or right) should work

## Actual Behavior
throws error that the file cannot be found

## Your Environment
* GraSPy version: 0.0.3
Anyone who installed with `pip` has this issue, otherwise they don't

**Comment by shiyussy** [comment]
I installed it from github, but still have this issue. The search path doesn't match the datasets location.

**Comment by bdpedigo** [comment]
Can you post what you ran and what the error was?

**Comment by bdpedigo** [comment]
And can you explain how you installed from github?

**Comment by shiyussy** [comment]
I installed it based on the instructions on https://github.com/neurodata/graspy/.
When I run `graspy.datasets.load_drosophila_right`, the error is 
No such file or directory: '...lib\\site-packages\\graspy-0.0.3-py3.7.egg\\graspy\\datasets\\drosophila\\right_adjacency.csv'
But I can find the corresponding file in '...lib\\site-packages\\graspy\\graspy\\datasets\\drosophila\\right_adjacency.csv'
If I copy the file and paste it to the first path, the error disappear.

**Comment by Kikiwink** [comment]
No folder named drosophila in the datasets folder when installing GraSPy from PyPl.
