### ISSUE TITLE
Clear outputs from tutorial notebooks

### ISSUE THREAD

**Issue by j1c** [neurodata/graspy#215]
Not sure which PRs have changed this, but all notebooks in tutorials should have no outputs. The point of these is to have netlify run them and build the outputs.

**Comment by bdpedigo** [comment]
Just had Kareef try this and it looked like they had not built on the
netify output when he pushed an empty notebook. Maybe there was something
like a `%matplotlib inline` missing in that notebook though? Has this
worked for you in the past?

**Comment by j1c** [comment]
Most likely? If netlify didn't error and there was no outputs, then I would guess `%matplotlib inline` is missing

**Comment by j1c** [comment]
Closed by #253
