### ISSUE TITLE
Primitives and Super Primitives to add

### ISSUE THREAD

**Issue by ebridge2** [neurodata/graspy#23]
Primitives
dimselect
ASE
LSE
OMNI

Super Primitives
Nonpar
Semipar
GClust
OOCASE

**Comment by jovo** [comment]
[jhu_primitives_graph_problems (1).pdf](https://github.com/neurodata/pygraphstats/files/2389964/jhu_primitives_graph_problems.1.pdf)

**Comment by jovo** [comment]
things to get clarification on:
- Gclass: i think this is LDA and QDA
- LSE: which special cases
- Nonpar: https://arxiv.org/abs/1409.2344, kernlab in R implements MMD

## things i don't care about in sprint 1
- OOCASE: too complicated
- VN
- SGM
- SGM
- community detection on large graphs

-
