### ISSUE TITLE
undo accidental push

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/graspy#238]
directed laplacian shouldn't be in master

**Comment by j1c** [comment]
:open_mouth:

**Comment by j1c** [comment]
Bruh i meant actually erase the two commits from history all together rather than make a new commit that undoes the previous two

**Comment by bdpedigo** [comment]
This was output of `git revert`, `git reset --hard {correct_commit}` and then `git push` is still giving me 
```
remote: error: Cannot force-push to a protected branch
To https://github.com/neurodata/graspy.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/neurodata/graspy.git'
```

I assume because of merge conflicts. Know of a way to do this without changing the branch permissions?

**Comment by bdpedigo** [comment]
also this https://github.com/isaacs/github/issues/1390

**Comment by bdpedigo** [comment]
@j1c i could disable branch checks, force push, then re-enable?

**Comment by j1c** [comment]
sure
