### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/graspy#240]
- [ ] Use more code examples in the docstrings
- [x] Add "extra hyperlinks to the documentation", I think from the tutorials to corresponding reference and from reference to tutorials
- [x] Make sure all attributes are documented
   - [x] Document attributes in Models 
   - [x] Check for others? 
- [x] Explain what pairplot is doing better
- [ ] Consider adding the code used to generate figure 2 into the docs. Though, this is approximately what the models tutorial is

**Comment by bdpedigo** [comment]
- [ ] Use more code examples in the docstrings
- [ ] Add "extra hyperlinks to the documentation", I think from the tutorials to corresponding reference and from reference to tutorials
- [ ] Make sure all attributes are documented. I think this is mostly an issue in `models`
- [ ] Explain what pairplot is doing better
- [ ] Consider adding the code used to generate figure 2 into the docs. Though, this is approximately what the models tutorial is

**Comment by j1c** [comment]
- [ ] Turn `CONTRIBUTING.md` to `rst` and put it in the documentation website as a tab

**Comment by bdpedigo** [comment]
- [ ] fix `MASE.fit_transform()` docs, says the output is (n_graphs, n_verts, n_components) but it should be (n_verts, n_components), as written. Unless we want `fit_transform` to output something else?
