### ISSUE TITLE
x11 display does not work with heatmap

### ISSUE THREAD

**Issue by heiidii** [neurodata/graspy#258]
## Expected Behavior
Tell us what should happen
When using graspy heatmap, a display window with the heatmap should appear
## Actual Behavior
Tell us what happens instead
No display appears with X11 forwarding (sshing into a remote server with x11 running for display)
## Template Code
```GraSPy
Paste the template code (ideally a minimal example) that causes the issue
from graspy.plot import heatmap
(just importing graspy seems to cause the x11 display to stop working)

```

## Full Traceback
```pytb
Paste the full traceback in case there is an exception

```

## Your Environment
* Python version:
* GraSPy version:

**Comment by bdpedigo** [comment]
@j1c seems this is because we override matplotlib backend
