### ISSUE TITLE
add common models that can be fit to graphs

### ISSUE THREAD

**Issue by ebridge2** [neurodata/graspy#26]
add models for SBM, ER, and ZI, inheriting from a base model class.

**Comment by bdpedigo** [comment]
@ebridge2 can we close?

**Comment by ebridge2** [comment]
this hasn't been completed, so I don't see why it would be closed, unless we no longer want to have model fitting in the package

**Comment by bdpedigo** [comment]
my b, I misunderstood the title then

**Comment by jovo** [comment]
@ebridge2 what is required for this to be completed?
please be detailed, as @dmannan will complete it :)

**Comment by j1c** [comment]
Done by #173
