### ISSUE TITLE
MutipleASE-like function that returns R matrices rather than latent positions

### ISSUE THREAD

**Issue by QuasiLegendre** [neurodata/graspy#260]
## Expected Behavior
The MutipleASE function returns latent positions rather than R matrices when participated in the Pipeline. I have a function that returns R matrices. In order to use MASEPipeline, I need to put that function in embed directory.
## Actual Behavior
The MutipleASE function returns latent positions rather than R matrices when participated in the Pipeline.

## Your Environment
* Python version: 3.7.3
* GraSPy version: 0.0.3(modified)

**Comment by bdpedigo** [comment]
Closing as we are sticking with current API for now
