### ISSUE TITLE
make diagonal augmentation work for weighted graphs

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/graspy#261]

**Comment by bdpedigo** [comment]
https://graspy.neurodata.io/reference/utils.html#graspy.utils.augment_diagonal

**Comment by gkang7** [comment]
When you say "work", would you like a particular operation done for each diagonal entries? Currently, it's just counting the nonzero entries and dividing them by (nverts-1), so would it suffice to change it by adding up the entries for weighted matrices and dividing them b y (nverts-1). Or for the purposes that this will used for, does taking a norm over the row make more sense?
