### ISSUE TITLE
Modify diag-aug and ASE default

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/graspy#287]
Diagonal augmentation leads to better estimation of latent positions, at least in unweighted case.
 - make the behavior for directed graphs be to average in and out degree 
 - make ASE use diag-aug before running as a default kwarg

**Comment by bdpedigo** [comment]
@j1c i forget do we want this for Omni too? Seems reasonable. Working on this now

**Comment by jovo** [comment]
for weighted graphs, i believe our default is 'cep-ptr' o 'diag-aug'.
so, even if weights are negative, assuming we ptr them, i think we still have the same procedure?
