### ISSUE TITLE
update requirements to scipy>=1.4

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/graspy#302]
Scipy 1.4
- has much faster linear assignment problem, making FAQ way faster
- has MGC, which we eventually want for new nonpar, signal subgraph

**Comment by PerifanosPrometheus** [comment]
I could take this one!

**Comment by PerifanosPrometheus** [comment]
Btw, my real name is (Giovanni) Giorgio but everybody calls me Giorgio.(I am sure you will get the reference : )

**Comment by alyakin314** [comment]
@PerifanosPrometheus 
fyi, no need to bother with mgc for nonpar, cuz we now have a hyppo background ( #336 ). idk the status of subgraphs.

> Btw, my real name is (Giovanni) Giorgio but everybody calls me Giorgio.(I am sure you will get the reference : )

i did not ...

**Comment by PerifanosPrometheus** [comment]
Thank you very much!

**Comment by bdpedigo** [comment]
@PerifanosPrometheus no need to worry about changing any code other than the requirements part

**Comment by PerifanosPrometheus** [comment]
@bdpedigo I am going to update the requirement in the [setup.py](https://github.com/neurodata/graspy/blob/master/setup.py#L13-22) and in the [requirement.txt](https://github.com/neurodata/graspy/blob/master/requirements.txt). I believe that should be enough, thank you for your advise!
