### ISSUE TITLE
Please develop a conda-forge feedstock

### ISSUE THREAD

**Issue by gdevenyi** [neurodata/graspy#335]
Thanks!

https://conda-forge.org/#add_recipe

**Comment by bdpedigo** [comment]
https://github.com/conda-forge/staged-recipes/pull/11388

**Comment by gmischl1** [comment]
Merged into conda-forge https://github.com/conda-forge/staged-recipes/pull/11388

**Comment by gdevenyi** [comment]
Fixed!
