### ISSUE TITLE
latent distribution test on directed inputs

### ISSUE THREAD

**Issue by alyakin314** [neurodata/graspy#358]
currently, latent distribution test does not support directed inputs. although there are lines that collapse together two embeddings
https://github.com/neurodata/graspy/blob/429728e454c3e1656cf213000e975b5c42d1d8ba/graspy/inference/latent_distribution_test.py#L104-L106
we do not know whether the behavior will be as expected. we need to 

- [ ] run simulations that verify that the behavior of the tests are as expected on directed inputs (i.e. they are valid and consistent)
- [x] stop throwing a directed input error
- [x] write tests and etc.

**Comment by alyakin314** [comment]
note: cep said that in the directed case the alignment (sign flips, or seedless procrustes, if that ever works) should be happening before concatenation.

**Comment by alyakin314** [comment]
@bdpedigo i will remove the the exception raised by directed inputs, if you don't mind. we still should test it's usage.

**Comment by bdpedigo** [comment]
do you mean test its usage then remove? yeah I'd be very happy to have that. probably wouldn't want to merge w/o a simple test on directed graphs tho.

**Comment by alyakin314** [comment]
by test do you mean a function in the test file (which there is, both with valid and with invalid inputs), or you mean a simulation?

**Comment by alyakin314** [comment]
also see #251
