### ISSUE TITLE
redo atlases using Jaewon's JSON mappings

### ISSUE THREAD

**Issue by ebridge2** [neurodata/graspy#36]

**Comment by j1c** [comment]
@ebridge2 

[Notebook](https://github.com/neurodata/graspy/blob/ndmg/docs/j1c/20180925/remapping.ipynb)
[Zip with jsons + updated niftis](https://github.com/neurodata/graspy/blob/ndmg/docs/j1c/20180925/ndmg_atlases.zip)

The following atlases were updated:
those in `func_atlases/label`:
+ `aal_res-1x1x1`
+ `aal_res-2x2x2`
+ `aal_res-4x4x4`
+ `brodmann_res-1x1x1`
+ `brodmann_res-2x2x2`
+ `brodmann_res-4x4x4`

The above 6 had floating point values like `0.9997711144387722`, but there are now 1:1 mapping to an integer.

those in `./labels`:
+ `AAL`
+ `HarvardOxford`

These 2 had strange numbering to regions. I'm not completely sure if these two need to be updated. If not, let me know.

All the other atlases remain unchanged, but there is still a JSON file for these. Lastly, all atlases are now uint32. Most were already uint32s, but some were in floats even though they only contained integers.

**Comment by ebridge2** [comment]
redid atlases with new atlases standardizing the pool for func and dwi, and remapped many of the dwi atlases/labels to standard space. Available here `aws s3 cp --no-sign-request s3://mrneurodata/resources/ndmg_atlases.zip ./'

**Comment by j1c** [comment]
@ebridge2 Can you clarify where to find the labels for below? or maybe someone already has it (maybe CEP or YP)?

- tissue
  - there are 3 labels. im guessing one is gray matter and white matter. what is the third?
- pp264
  - where is this from? perhaps we should change to a more useful name
- desikan
  - this is from the 2006 paper. i have 70 labels found on freesurfer, but none of the labels make any sense (obvious markers are not where I expect them to be).
- DK
  - i think this is from the 2012 paper from mindboggle? seems almost identical to desikan, but has 13 regions?

I think there were already some preprocessing done on the desikan and DK ones...

**Comment by loftusa** [comment]
New labels are here: https://github.com/neurodata/graspy/blob/ndmg/notebooks/j1c/20181012/label_updated.zip

Missing labels: desikan, DK, pp264, tissue
