### ISSUE TITLE
hsic works with kernels, not distances

### ISSUE THREAD

**Issue by alyakin314** [neurodata/graspy#363]
unlike all other tests used as backends of the latent distribution test (via hyppo), HSic works on kernels, not distances (it is actually almost identical to DCorr, except that it expects a kernel function, not a distance, and hence flips the sign on the test statistic). we currently do nothing about that. some options to consider are:

- removing it completely (not a big loss, since, once again, DCorr does a similar thing)
- leaving it as is, but expecting a user to provide a callable metric. (if they try to provide "euclidean" - raise an exception)
- wrapping the currently used dissimilarity metrics into similarity measures (very obvious how to do it for the gaussian kernel. less so obvious for l1/l2, but obviously possible (for example by subtracting all from the max or doing 1/. )
- some sort of a combination of the two right above: for example, expecting a callable metric, but using a gaussian kernel if unspecified.

**Comment by alyakin314** [comment]
i might be missing something obvious, but I legitimately have no idea why was it valid and consistent when we ran those simulations, if it expects a kernel, not a distance, and we were providing it with the latter. 

@sampan501 maybe you know?

**Comment by sampan501** [comment]
If I'm not wrong, I think @bvarjavand did the transformation for kernel to distance as specified in the exact equivalence paper. In that case, the test should be valid

**Comment by alyakin314** [comment]
@sampan501 i do not exactly understand what that means. the way you implement hsic is by using the transformation of kernel to distance, computing the distance (i.e. dissimilarity) matrix, and then using dcorr, since EE says that this is identical to just using hsic:
https://github.com/neurodata/hyppo/blob/da63f814023f956defd0f773b5eb7a59b4f540fa/hyppo/independence/hsic.py#L128-L136
this makes total sense. but... if I were to provide you with a distance to begin with, you would subsequently transform it as 1 - K / max(K) to a kernel and then use dcorr, but that can't be the right thing to do?
unless you are saying that @bvarjavand implemented a way to check whether something is a kernel or a distance and convert it, but I cannot find anything of this sort in hyppo.

**Comment by alyakin314** [comment]
"The population HSIC is zero at independence, so the sample is unlikely to be independent when the empirical HSIC is large." ( http://www.gatsby.ucl.ac.uk/~gretton/indepTestFiles/indep.htm ).

that is, both dcorr and hsic reject for the large positive values of the statistic, so it makes sense that it was valid, but we were still using it wrong and should be providing it with kernels.

**Comment by sampan501** [comment]
Yes I meant I think @bvarjavand implemented it this way since he had asked me similar, but he probably knows better. But I agree with your assessment that you should provide kernels
