### ISSUE TITLE
returning test statistic in LDT

### ISSUE THREAD

**Issue by alyakin314** [neurodata/graspy#370]
some practitioners (read: Vince, cep) only care about the test statistic and not the p-value. obviously one can still extract it if they perform the full test. however, that wastes time and resources. one can set the number of iterations to 1 to minimize that, but we can still do less. i propose to allow the number of permutations to be set to 0 (hyppo allows that, so really it is just a change in argument check). i am happy to do this, but:

this brings up the following questions: what should be happening to the fit_predict in that case? should it return the test statistic instead? or the p-value of 1? or NaN? should we be raising warnings?

and on a larger scale: should we really have this API? should fit predict return p-value, or a tuple of a p-value and a test statistic, like many other tests in python? furthremore, should it really be a class? once again, most tests in python that i have seen (scipy, statsmodels) are functions, not classes.

**Comment by bdpedigo** [comment]
agree that wanting test statistic and not the null is a totally valid use case, I also want that. 

number of permutations = 0 is not that intuitive to me (i did not even realize this was the case and always end up calling some _statistic( ) private method which is also not ideal). some users may not know that much about what is happening behind the scenes (e.g. permutation test) to make this intuitive. 

based on your comments above, i feel like maybe we are stretching the sklearn api a bit too far here. I don't have a problem with it being a class though, but don't feel too strongly, do you have specific examples of stuff that you like better? 

I'm wondering if a class with methods like .test() and .statistic() would make the most sense? not sure but that is the best compromise i see so far.

**Comment by alyakin314** [comment]
i offer to allow using number of permutations = 0, followed by ._statistic for now. and subsequently we can change the api.

i certainly do not mind .test() and .statistic(). this feels like something that would be more intuitive to an average user than fit() and fit_predict(). that said, i am not yet convinced that it is strictly better than having a function.

i can change the tests from fit to test in the current pr, if you feel strongly about it. though i should note that it will break anything that currently uses the test, as it is quite not backward-compatible.

**Comment by bdpedigo** [comment]
i'll take whatever you can offer!

I don't feel strongly about what you do for now, but ultimately .test() and .statistic() or just having a func will make more sense. happy to have those change later tho if you don't want to do it now. 

I'm curious, what all would the function return? just test statistic and p-value? what if the user wants to see test statistic for all permutations or something like that (for plotting null vs observed, say)? not sure how other stats funcs usually handle this

**Comment by alyakin314** [comment]
the consensus for now is to change it to a function. either one that returns test_statistic+p_value+null_distribution. or the one that returns test_statistic+p_value+(null_distribution, optional). i'll research python conventions on permutation test implementations more.

**Comment by alyakin314** [comment]
will be closed by #366, as that allows 0 permutations. for api change see #375 .
