### ISSUE TITLE
write some "extended" or "advanced topics" tutorials 

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/graspy#401]
- [ ] regularization, ptr
- [ ] alignment of embeddings (when we have the align module) 
- [ ] embedding CLT 
- [ ] ase vs lse vs n2v
- [ ] omni vs mase

**Comment by bdpedigo** [comment]
@alyakin314 i think having a place to explain embedding alignment w.r.t. nonpar is important, esp. given #411. Just leaving a note as a reminder for us or NDD. will be easier to explain once we have `graspy.align`

**Comment by bdpedigo** [comment]
breaking out into separate issues, see #442 #443

**Comment by alyakin314** [comment]
of some relevance:
https://nbviewer.jupyter.org/url/alyakin314.github.io/assets/seedless_2.ipynb
Ali, Carey and Youngser also have another simulated example in which one has to use seedless to do sound inference.
