### ISSUE TITLE
No module named 'sklearn.mixture._gaussian_mixture 

### ISSUE THREAD

**Issue by dfrancisco1998** [neurodata/graspy#412]
I am trying to make a conda environment to start playing around with the graspy tutorials and it keeps giving me "No module named 'sklearn.mixture._gaussian_mixture". In an effort to remedy this I uninstalled scikit-learn and reinstalled it with version 0.19.2. But I get a new error in the install saying my python version is too high to be compatible. 

I set up the conda environment using "conda create --name ndd". I then went to install all the dependencies Python 3.8.5, scipy-1.5.0, scikit-learn-0.23.2(and then subsequently  0.19.2.) , networkx-2.5, pandas-1.1.1, numpy-1.19.1. I then installed graspy using the github method as explained on the github page for graspy.

**Comment by bdpedigo** [comment]
Hi @dfrancisco1998 - currently we aren't officially supporting python 3.8 ([see here](https://github.com/neurodata/graspy#python-requirements)), though that is one of the issues I want someone to tackle for sprint 0. 

Can you try specifying `python=3.7` when making your environment, and see if that works?

**Comment by dfrancisco1998** [comment]
Yep will do! I did see that in sprint 0 right after I had sent my initial
zoom request, which is a little funny. Would I be able to tackle that
issue(although if I may be frank I am unsure what it entails but happy to
learn!).

Sincerely,
David

**Comment by bdpedigo** [comment]
sure, @dfrancisco1998, if you comment on #277 then I will be able to assign you that issue.

**Comment by bdpedigo** [comment]
closing this issue, is a problem with #277.
