### ISSUE TITLE
What plots would be useful?

### ISSUE THREAD

**Issue by j1c** [neurodata/graspy#45]
First I think seaborn is a good choice. ggplot for python hasn't been developed in over 2 years so while ggplot is nice, I don't think I'm going to use it. Not the biggest fan of plotly. Thoughts appreciated. 

So for actual plots:
1. Function for plotting 1 or more adjacency/similarity/dissimilarity matrices as heatmaps
2. Pairwise scatter plots. So given X \in R^{n x d}, it plots each pairs of dimensions as scatter plots
3. A generic scatter plot. Given X \in R^n and Y \in R^n, just makes a scatter plot.
4. ??

@jovo @ebridge2 @bdpedigo

**Comment by bdpedigo** [comment]
Agree with seaborn 

What about plotting the result of generic clusterings? Could build off of scatter plots mentioned above, but it would be nice to be able to visualize either class labels or errors if the true labels are known

**Comment by ebridge2** [comment]
Would recommend plotly + pandas. It's actually super ez w pandas, which i
hadnt used before to do adjacency matrix related plots; Iwould imagine the
scatter plots needed for the proposition below are similarly trivial. Check
one of my weeklies in `docs`; the resulting plots are p nice and are like,
sub 10 lines of code you can steal; also they are interactive. As a
starting pt, I'd revommend the ones in the R package rn; namely, heatmap of
adj matrix,

scatter plot of sparse adj matrix where x and y are still vertices, but
strength of an edge is shown by the size of a point at that particular (x,
y)),

 some way of overlapping n scatters with n different edge lists shared
vertices using color to indicate which adjacency matrix a particular edge
is from, and normalizing the point size btwn 0, 1,

and a way to overlap a heatmap with n scatters having shared vertices.
Also, there should be the option to show summary statistics as marginals in
the x and y axis for all types of matrix plots; ie, vertex degree for
instance. See our connectome coding paper for details; @jovo please post a
link/invite them to the overleaf? that has all of the above 4.

Eric

**Comment by j1c** [comment]
@ebridge2 Are they really voronois for second and third figures? I thought voronoi diagrams have straight edges not curves?
