### ISSUE TITLE
Things to do within next week

### ISSUE THREAD

**Issue by bdpedigo** [neurodata/graspy#58]
# Pedigo
- [x] LCC
- [x] diag aug
- [x] Anibal's error/is_close(), unless someone already fixed/clarified that
- [x] Protect laplacian normalization against undirected graphs
- [x] Change how `form` kwarg gets passed to LSE
- [x] Let PTR take kwargs
- [x] RDPG
  - [x] fix min()
  - [x] actual simulation
  - [x] add tests
- [x] Laplacian fails when node degree 0 
- [x] Add alpha param for plotting 
  - [x] heatmap: use diverging colormap by default if there are both negative and pos numbers

# J1C

- [x] sphinx docs
- [x] omni
  - [x] docs that it works on tensors
  - [x] docs that say you should get a tuple back if asymmetric graphs
- [x] mds
  - [x] modify cmds to work on matrices
    - [x] test for matrix
  - [x] Dimselect in MDS
  - [x] Typecheckingin MDS
- [x] rewrite SVD to use svd, svds, and randomized_svd
  - [x] Error catching in selectSVD
  - [x] remove lpm and save UD^1/2, VD^1/2, and D
- [x] rewrite sims to have the following:
  - [x] sampling class that operates on a P matrix
    - [x] sbm, rdpg, erdos renyi (n p) models
  - [x] sampling class that operates on number of edges
    - [x] erdoes renyi - (n m) model
    - [x] zero inflated (n m) models
  - [x] sampling class for edge weights

**Comment by j1c** [comment]
Nevermind. Omni works fine with directed graphs. Ill add a test for directed case.
