### ISSUE TITLE
Drishti: Continued Graph Classification

### ISSUE THREAD

**Issue by dmannan** [neurodata/graspy#90]
- Switch to classifying graphs from ndmg

- Classify (sex and then hopefully ADHD or some other neurological disorder of interest) the ndmg graphs using:
1. Jaewon's graph to vector algorithm to extract features from the graphs. Run the output vector through Rerf for classification.
2. Maybe try the technique suggested in this paper: https://arxiv.org/abs/1801.07683

DoD: Jupyter notebooks that take in ndmg graphs (adjacency matrix), and output a label for the class prediction (sex of the individual, or presence/absence of ADHD (eventually))

**Comment by jovo** [comment]
seems very promising.  seems like something you can do over break?
would require porting the code for signal subgraph to python, 
should be easy, given the existence of mgcpy...

**Comment by j1c** [comment]
Can I close given @vikramc1 is working on this now? @dmannan
